sudo: required
dist: trusty

language: haxe

# Add encrypted API key
env:
  global:
    - secure: FZomAMKPplIjhEKCAWbzh2Mkz7n3oPL7Ze4gvYMQFnoEm+pTHhvBX+HMqtuQvBImhNvnqQaMVBS+YnRapzHOMK5Z45v0/oUTACXwJQT8+3wh6Pee0pnuJ033XPx8SARnNc/AUjD9wP+R/fwDCE480ZunhVSLfqh61PRoQlmYQnBvYv74iT4SFnvzSU8HK0dMIde9jpHT1lYcJ1wc/1MdOgRWOk3wGfUDjqzzrw+qgziW/CZ0Akld9mMpd72ULWqjudCZIgXrsZ52wC373h3yhRkezF3J2e8cheeEti6SVR/Ffy3kbfdK+vGSLsK6DlXGKAC4ywCJHwaSb9YPUwiMq6n0BXJz0ojXfPVd7Bpcg/R7AfiuoQj9VQBn0J3aG9ZEbNjMAEMJP/oX+s+FnVIJ3odrHrNIG6uW69zG7UGnskIoDutCW/rzO1Khq3MtkbBtVlB0LwU45PjIDN8bj0brmHmoPkJe+LcGwta02AiCaj1zBikirWe5M0d8jR6iuLqIvwV94RkgO5uYw5kVcBvFCKoK6ycly4UtIohtis66qliz6ga+fX6RQgsrMePFYsgBqx3JNPBl0+Bh2yFV7zNWML2r3eMY2tIXDJ6psLuKT1Rt8uNZLAoz1YnI/EqoTxn5GoyLovgEApBqzs2iyeMi+FsxkMID0b4/zNMtwEKYoBA=
os:
  - linux

# Blacklist
branches:
  only:
    - master

# Build the project
script:
  - haxe geometrize-gallery.hxml
  - haxe geometrize-gallery.hxml

# Deploy the generated site using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/bin
  github_token: $GITHUB_API_KEY
  # Sets the CNAME file for the custom domain (not enough to just set it on the Github page settings)
  fqdn: gallery.geometrize.co.uk
  on:
    branch: master